controle_NTI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('',   views.InicioView.as_view(), name='inicio'),
    path('usuario/', include('user.urls', namespace="usuario")),
    path('equipamento/', include('equipamento.urls', namespace="equipamento")),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

equipamento/urls.py
from django.urls import path, include
from . import views

app_name = 'equipamento'

urlpatterns = [
    path('adicionar/',   views.AdicionarEquipamentoView.as_view(),
         name='adicionar-equipamento'),
    path('marcas/',   views.MarcaView.as_view(), name='marcas'),
    path('modelo/<int:pk>/',   views.ModeloView.as_view(), name='modelo'),

]

user/urls.py
from django.urls import path, include
from . import views

app_name = 'user'

urlpatterns = [
    path('login/',   views.LoginView.as_view(), name='login'),

]

equipamento/models.py
from django.db import models
from django.contrib.auth.models import User


class Marca(models.Model):

    nome = models.CharField(blank=False, unique=True, max_length=200)
    data_cadastro = models.DateTimeField(auto_now_add=True)
    obs = models.CharField(blank=False, max_length=400)

    def __str__(self):
        return 'Nome: %s' % (self.nome)


class Conjunto(models.Model):

    identificação = models.CharField(blank=False, max_length=200)
    data_cadastro = models.DateTimeField(auto_now_add=True)
    obs = models.CharField(blank=False, max_length=400)


class Modelo(models.Model):
    marca = models.ForeignKey(
        Marca, on_delete=models.SET_NULL, related_name='marca', blank=True, null=True)
    nome = models.CharField(blank=False, max_length=300)
    tipo = models.CharField(blank=True, max_length=100)
    descricao = models.CharField(blank=False, max_length=400)
    obs = models.CharField(blank=False, max_length=400)
    data_cadastro = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Nome: %s' % (self.nome)


class Equipamento(models.Model):

    modelo = models.ForeignKey(
        Modelo, on_delete=models.SET_NULL, related_name='modelo', blank=True, null=True)
    conjunto = models.ForeignKey(
        Conjunto, on_delete=models.SET_NULL, related_name='conjunto', blank=True, null=True)
    numero_de_serie = models.CharField(blank=True, max_length=100)
    patrimonio = models.CharField(blank=True, null=True, max_length=100)
    departamento = models.CharField(blank=True, null=True, max_length=100)
    mesa = models.CharField(blank=True, null=True, max_length=50)
    ramal_proximo = models.CharField(blank=True, null=True, max_length=50)
    usuario = models.CharField(blank=True, null=True, max_length=100)
    so = models.CharField(blank=True, null=True, max_length=50)
    data_cadastro = models.DateTimeField(auto_now_add=True)
    ponto_de_rede = models.CharField(blank=True, null=True, max_length=50)
    status = models.CharField(blank=True, null=True, max_length=100)
    obs = models.CharField(blank=False, max_length=400)

user/models.py
from django.db import models

# Create your models here.

controle_NTI/views.py
from django.views.generic import TemplateView
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth.mixins import LoginRequiredMixin


class InicioView(LoginRequiredMixin, TemplateView):

    template_name = 'inicio.html'

equipamento/views.py
from django.views.generic import TemplateView
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse

from .models import Marca, Modelo


class AdicionarEquipamentoView(LoginRequiredMixin, TemplateView):

    template_name = 'equipamentos/adicionar.html'


class MarcaView(TemplateView):

    def post(self, request):

        nome = request.POST['nome']
        obs = request.POST['obs']

        if not Marca.objects.filter(nome=nome):
            m = Marca.objects.create(nome=nome, obs=obs)
            return JsonResponse({'evento_id': 1, 'id_marca': m.id})

        return JsonResponse({'evento_id': 2, 'msg': 'Marca ja está cadastrada'})

    def get(self, request):

        marcas = Marca.objects.all()

        marcaArray = []
        for marca in marcas:
            marcaArray.append(
                {'id': marca.id, 'nome': marca.nome, 'obs': marca.obs})

        return JsonResponse(marcaArray, safe=False)


class ModeloView(TemplateView):

    def post(self, request, pk):

        nome = request.POST['nome']
        tipo = request.POST['tipo']
        desc = request.POST['desc']
        obs = request.POST['obs']
        marcar = Marca.objects.get(id=pk)

        if not Modelo.objects.filter(marca=marcar, nome=nome):
            m = Modelo.objects.create(
                marca=marcar, tipo=tipo, nome=nome, descricao=desc, obs=obs)
            return JsonResponse({'evento_id': 1, 'id_modelo': m.id})

        return JsonResponse({'evento_id': 2, 'msg': 'Modelo ja está cadastrada'})

    def get(self, request, pk):
        modelos = Modelo.objects.filter(marca=pk)

        modeloArray = []
        for modelo in modelos:
            modeloArray.append(
                {'id': modelo.id, 'nome': modelo.nome, 'obs': modelo.obs})

        return JsonResponse(modeloArray, safe=False)

user/views.py
from django.shortcuts import render
from django.views.generic import CreateView, FormView, UpdateView, TemplateView
from django.urls import reverse_lazy, reverse
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render_to_response, redirect


class LoginView(TemplateView):

    success_url = reverse_lazy('inicio')
    template_name = 'login.html'

    def post(self, request):
        username = self.request.POST.get('username', '')
        password = self.request.POST.get('password', '')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return(redirect('inicio'))
            else:
                return render_to_response("login.html",
                                          {'invalid': True})
        else:
            return render_to_response("login.html",
                                      {'invalid1': True})

equipamento/templates/adicionar.html
{% extends 'inicio.html' %}
{% block content %}
{% load static %}
<div class="wrapper fadeInDown">
    <div id="formContent">
        <!-- Tabs Titles -->

        <!-- Icon -->
        <div class="fadeIn first">
            <img src="{% static 'img/img-login.png' %}" id="icon" alt="User Icon" />
        </div>

        <!-- Login Form -->
        <form action="{% url 'user:login' %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-2"></div>
                <div class="col-8">
                    {% if invalid %}
                    <div class="alert alert-danger" role="alert">
                        Conta desativada
                    </div>
                    {% endif %}
                    <!-- Login Form -->
                    {% if invalid1 %}
                    <div class="alert alert-danger" role="alert">
                        Usuario ou Senha incorreto.
                    </div>
                    {% endif %}
                </div>
                <div class="col-2"></div>
            </div>
            <input type="text" id="login" class="fadeIn second" name="login" placeholder="Usuário" />
            <input type="password" id="password" class="fadeIn third" name="login" placeholder="Senha" />
            <input type="submit" class="fadeIn fourth" value="Entrar" />
        </form>

        <!-- Remind Passowrd 
    <div id="formFooter">
      <a class="underlineHover" href="#">Forgot Password?</a>
    </div>-->
    </div>
</div>
{% endblock %}

templates/equipamentos/adicionar.html
{% extends 'inicio.html' %}
{% block content %}
{% load static %}
{% csrf_token %}
<div class="wrapper">
    <form id="regForm" action="">
        {% csrf_token %}
        <h1>Cadastrar novo equipamento:</h1>

        <!-- One "tab" for each step in the form: -->
        <div class="tab">
            <div class="row">
                <div class="col-2"></div>
                <div class="col-4">
                    <div class="form-group">
                        <label for="marca">Marca</label>
                        <select class="form-control" id="marca" onchange="marcaChange(event)">
                            <option value="0">-------</option>
                        </select>
                    </div>
                </div>
                <div class="col-2">
                    <button type="button" class="align-self-end btn btn-primary" data-toggle="modal"
                        data-target="#modalMarca" style="width: 100%; margin-top: 30px;">
                        Adicionar
                    </button>
                </div>
                <div class="col-2"></div>
            </div>
            <div class="row">
                <div class="col-2"></div>
                <div class="col-4">
                    <div class="form-group">
                        <label for="modelo">Modelo</label>
                        <select class="form-control" id="modelo" disabled onchange="selectModelo()">
                            <option value="0">-------</option>
                        </select>
                    </div>
                </div>
                <div class="col-2">
                    <button type="button" class="align-self-end btn btn-primary" id="bt_addModelo" data-toggle="modal"
                        data-target="#modalModelo" style="width: 100%; margin-top: 30px;" disabled>
                        Adicionar
                    </button>
                </div>
                <div class="col-2"></div>
            </div>
        </div>

        <div class="tab">Contact Info:
            <p><input placeholder="E-mail..." oninput="this.className = ''"></p>
            <p><input placeholder="Phone..." oninput="this.className = ''"></p>
        </div>

        <div class="tab">Birthday:
            <p><input placeholder="dd" oninput="this.className = ''"></p>
            <p><input placeholder="mm" oninput="this.className = ''"></p>
            <p><input placeholder="yyyy" oninput="this.className = ''"></p>
        </div>

        <div class="tab">Login Info:
            <p><input placeholder="Username..." oninput="this.className = ''"></p>
            <p><input placeholder="Password..." oninput="this.className = ''"></p>
        </div>

        <div style="overflow:auto;">
            <div style="float:right;">
                <button type="button" id="prevBtn" class="align-self-end btn btn-primary"
                    onclick="nextPrev(-1)">Anterior</button>
                <button type="button" id="nextBtn" class="align-self-end btn btn-primary" onclick="nextPrev(1)"
                    disabled>Proximo</button>
            </div>
        </div>

        <!-- Circles which indicates the steps of the form: -->
        <div style="text-align:center;margin-top:40px;">
            <span class="step"></span>
            <span class="step"></span>
            <span class="step"></span>
            <span class="step"></span>
        </div>

    </form>
</div>

<!-- Modal Adicionar Marca-->
<div class="modal fade" id="modalMarca" tabindex="-1" role="dialog" aria-labelledby="modalMarcaLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalMarcaLabel">Cadastrar Marca</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="nome">Nome:</label>
                    <input type="text" class="form-control" id="nomeMarca" placeholder="Nome da marca">
                    <small id="marcaErro" class="form-text text-muted" hidden>
                        <p style="color: red;">* Marca ja está
                            cadastrada</p>
                    </small>
                    <small id="marcaErro2" class="form-text text-muted" hidden>
                        <p style="color: red;">* Campo
                            obrigatório</p>
                    </small>
                </div>
                <div class="form-group">
                    <label for="obs">Observação:</label>
                    <textarea class="form-control" name="obs" id="obsMarca" cols="30" rows="5"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" onclick="cadastraMarca()">Savar</button>
            </div>
        </div>
    </div>
</div>


<!-- Modal Adicionar Modelo-->
<div class="modal fade" id="modalModelo" tabindex="-1" role="dialog" aria-labelledby="modalModeloLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="titulo_modelo">Cadastrar Modelo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="nomeModelo">Nome:</label>
                    <input type="text" class="form-control" id="nomeModelo" placeholder="Nome do modelo">
                    <small id="modeloErro" class="form-text text-muted" hidden>
                        <p style="color: red;">* Modelo ja está
                            cadastrada</p>
                    </small>
                    <small id="modeloErro2" class="form-text text-muted" hidden>
                        <p style="color: red;">* Campo
                            obrigatório</p>
                    </small>
                </div>
                <div class="form-group">
                    <label for="tipo">Tipo:</label>
                    <select class="form-control" id="tipo">
                        <option value="Gabinete">Gabinete</option>
                        <option value="Impressora">Impressora</option>
                        <option value="Monitor">Monitor</option>
                        <option value="Mouse">Mouse</option>
                        <option value="Notebook">Notebook</option>
                        <option value="Roteador">Roteador</option>
                        <option value="Servidor">Servidor</option>
                        <option value="Scanner">Scanner</option>
                        <option value="Switch">Switch</option>
                        <option value="Teclado">Teclado</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="descricaoModelo">Descrição:</label>
                    <textarea class="form-control" name="descricao" id="descricaoModelo" cols="30" rows="5"></textarea>
                </div>
                <div class="form-group">
                    <label for="obsModelo">Observação:</label>
                    <textarea class="form-control" name="obs" id="obsModelo" cols="30" rows="5"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" onclick="CadastraModelo()">Savar</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/inicio.html
<!DOCTYPE html>
<html lang="pt">
{% load static %}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="stylesheet" id="bootstrap-css" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

    <title>Projeto</title>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">NTI</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Inicio <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/equipamento/adicionar/">Adicionar Equipamento</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

</body>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>
<script src="{% static 'js/cadastroEquipamentos.js' %}"></script>

</html>

user/templates/login.html
<!DOCTYPE html>
<html lang="pt">
{% load static %}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="stylesheet" id="bootstrap-css" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

    <title>Projeto</title>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Bootstrap core CSS -->

    <!-- Custom fonts for this template -->

    <!-- Custom styles for this template -->
</head>

<body>
    {% if user.is_authenticated %}
    <script>
        window.location = "/";
    </script>
    {% else %}
    <div class="wrapper fadeInDown">
        <div id="formContent">
            <!-- Tabs Titles -->

            <!-- Icon -->
            <div class="fadeIn first">
                <img src="{% static 'img/img-login.png' %}" id="icon" alt="User Icon" />
            </div>

            <!-- Login Form -->
            <form action="{% url 'user:login' %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-2"></div>
                    <div class="col-8">
                        {% if invalid %}
                        <div class="alert alert-danger" role="alert">
                            Conta desativada
                        </div>
                        {% endif %}
                        <!-- Login Form -->
                        {% if invalid1 %}
                        <div class="alert alert-danger" role="alert">
                            Usuario ou Senha incorreto.
                        </div>
                        {% endif %}
                    </div>
                    <div class="col-2"></div>
                </div>
                <input type="text" id="login" class="fadeIn second" name="login" placeholder="Usuário" />
                <input type="password" id="password" class="fadeIn third" name="login" placeholder="Senha" />
                <input type="submit" class="fadeIn fourth" value="Entrar" />
            </form>

            <!-- Remind Passowrd 
        <div id="formFooter">
          <a class="underlineHover" href="#">Forgot Password?</a>
        </div>-->
        </div>
    </div>
    {% endif %}
</body>

</html>